[package]
name = "roaring"
version = "0.10.6"
rust-version = "1.65.0"
authors = ["Wim Looman <wim@nemo157.com>", "Kerollmops <kero@meilisearch.com>"]
description = "A better compressed bitset - pure Rust implementation"

documentation = "https://docs.rs/roaring"
repository = "https://github.com/RoaringBitmap/roaring-rs"

readme = "README.md"
keywords = ["roaring", "data-structure", "bitmap"]
categories = ["data-structures"]
edition = "2021"

license = "MIT OR Apache-2.0"

[dependencies]
bytemuck = { version = "1.16.1", optional = true }
byteorder = { version = "1.5.0", optional = true }
rkyv = "0.7.44"
serde = { version = "1.0.203", optional = true }

[features]
default = ["std"]
serde = ["dep:serde", "std"]
simd = []
std = ["dep:bytemuck", "dep:byteorder"]

[dev-dependencies]
proptest = "1.5.0"
serde_json = "1.0.120"
bincode = "1.3.3"

[profile.test]
opt-level = 2
